# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='datetime_connection',
            new_name='last_datetime_connection',
        ),
        migrations.RemoveField(
            model_name='network',
            name='is_active',
        ),
    ]
