# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0002_auto_20161028_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='network_name',
            field=models.CharField(max_length=30, verbose_name='Network name'),
        ),
    ]
