# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0003_auto_20161028_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='ip',
            field=models.CharField(max_length=15, verbose_name='Ip'),
        ),
    ]
