# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0004_auto_20161028_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='last_datetime_connection',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last connection datetime'),
        ),
    ]
